# Example Configuration for Calum Worthy AI Assistant
# Copy this to .streamlit/secrets.toml and fill in your actual values

# Required API Keys
OPENAI_API_KEY = "sk-your-openai-api-key-here"
ACTIVELOOP_TOKEN = "your-activeloop-token-here"

# Optional - LangSmith for tracing and monitoring
LANGSMITH_API_KEY = "lsv2_pt_your-langsmith-key-here"
LANGCHAIN_TRACING_V2 = "true"
LANGCHAIN_PROJECT = "calum-worthy-chatbot-api"

# System Configuration
DATASET_NAME = "calum_v10"
PERSONA_PROMPT_FILE = "calum_prompt_v2.1.yaml"
ACTIVELOOP_ORG_ID = "your-activeloop-organization-id"

# Instructions:
# 1. Get OpenAI API key from: https://platform.openai.com/api-keys
# 2. Get ActiveLoop token from: https://app.activeloop.ai/
# 3. Get LangSmith key from: https://smith.langchain.com/ (optional)
# 4. Replace "your-activeloop-organization-id" with your actual org ID
# 5. Save this file as .streamlit/secrets.toml
